CREATE TABLE IF NOT EXISTS activities (
	id INT PRIMARY KEY AUTO_INCREMENT,
	event_id BIGINT NOT NULL,
	name VARCHAR(100) NOT NULL,
	duration_minutes INT NOT NULL,
	group_size INT NOT NULL,
	description TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	INDEX idx_activities_event (event_id),
	FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;